import { StyleSheet } from "react-native";

const global_styles = StyleSheet.create({
    flexCenter:{
      justifyContent:"center",
      alignContent:"center"
    },
    text_xl:{
        fontSize:48
    },
    text_lg:{
        fontSize:32
    },
    text_md:{
        fontSize:24
    },
    text_sm:{
        fontSize:12
    },
    p_xl:{
        padding:25
    },
    p_lg:{
        padding:20
    },
    p_md:{
        padding:15
    },
    p_sm:{
        padding:10
    },
    p_h_xl:{
        paddingHorizontal:25
    },
    p_h_lg:{
        paddingHorizontal:20
    },
    p_h_md:{
        paddingHorizontal:15
    },
    p_h_sm:{
        paddingHorizontal:10
    },
    p_v_xl:{
        paddingVertical:25
    },
    p_v_lg:{
        paddingVertical:20
    },
    p_v_md:{
        paddingVertical:15
    },
    p_v_sm:{
        paddingVertical:10
    },
    m_xl:{
        margin:25
    },
    m_lg:{
        margin:20
    },
    m_md:{
        margin:15
    },
    m_sm:{
        margin:10
    },
    m_h_xl:{
        marginHorizontal:25
    },
    m_h_lg:{
        marginHorizontal:20
    },
    m_h_md:{
        marginHorizontal:15
    },
    m_h_sm:{
        marginHorizontal:10
    },
    m_v_xl:{
        marginVertical:25
    },
    m_v_lg:{
        marginVertical:20
    },
    m_v_md:{
        marginVertical:15
    },
    m_v_sm:{
        marginVertical:10
    }
})

export default global_styles;